version: "3.0"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  web:
    image: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8080:80"
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./node/src/:/usr/src/app/src
    ports:
      - "3001:3001"
